gsap.registerPlugin(Observer);
const sections=[...document.querySelectorAll('.scene')], images=[...document.querySelectorAll('.bg')], outers=[...document.querySelectorAll('.outer')], inners=[...document.querySelectorAll('.inner')], headings=[...document.querySelectorAll('.heading')], dots=[...document.querySelectorAll('.dot')], counter=document.querySelector('.counter .current'), fill=document.querySelector('.fill');
function splitHeading(el){const html=el.innerHTML;const holder=document.createElement('div');holder.innerHTML=html;function walk(node){if(node.nodeType===3){const frag=document.createDocumentFragment();[...node.textContent].forEach(c=>{const s=document.createElement('span');s.className='char';s.textContent=c===' '?'\u00A0':c;frag.appendChild(s)});node.replaceWith(frag)}else if(node.nodeType===1){[...node.childNodes].forEach(walk)}}[...holder.childNodes].forEach(walk);el.innerHTML=holder.innerHTML;return [...el.querySelectorAll('.char')]}
const chars=headings.map(splitHeading);let current=-1,animating=false;
gsap.set(outers,{yPercent:100});gsap.set(inners,{yPercent:-100});
function updateUI(i){counter.textContent=String(i+1).padStart(2,'0');fill.style.width=((i+1)/sections.length*100)+'%';dots.forEach((d,n)=>d.classList.toggle('active',n===i))}
function go(index,direction){if(index<0||index>=sections.length){animating=false;return}animating=true;const factor=direction===-1?-1:1;const tl=gsap.timeline({defaults:{duration:1.08,ease:'power2.inOut'},onComplete:()=>animating=false});if(current>=0){gsap.set(sections[current],{zIndex:0});tl.to(images[current],{yPercent:-11*factor,scale:1.045},0).to(sections[current],{autoAlpha:0,duration:.18},.9)}gsap.set(sections[index],{autoAlpha:1,zIndex:1});tl.fromTo([outers[index],inners[index]],{yPercent:i=>i?-100*factor:100*factor},{yPercent:0},0).fromTo(images[index],{yPercent:11*factor,scale:1.07},{yPercent:0,scale:1},0).fromTo(chars[index],{autoAlpha:0,yPercent:135*factor},{autoAlpha:1,yPercent:0,duration:.82,ease:'power3.out',stagger:{each:.012,from:'random'}},.22).fromTo(sections[index].querySelectorAll('.eyebrow,.sub,.actions'),{autoAlpha:0,y:20*factor},{autoAlpha:1,y:0,duration:.55,stagger:.08,ease:'power2.out'},.55);current=index;updateUI(index)}
Observer.create({type:'wheel,touch,pointer',wheelSpeed:-1,tolerance:10,preventDefault:true,onDown:()=>!animating&&go(current-1,-1),onUp:()=>!animating&&go(current+1,1)});
window.addEventListener('keydown',e=>{if(animating)return;if(['ArrowDown','PageDown',' '].includes(e.key))go(current+1,1);if(['ArrowUp','PageUp'].includes(e.key))go(current-1,-1)});
[...new Set(images.map(i=>getComputedStyle(i).backgroundImage.match(/url\(["']?(.*?)["']?\)/)?.[1]).filter(Boolean))].forEach(src=>{const im=new Image();im.src=src});
go(0,1);